### ISSUE TITLE
[Refactor] stock_service 분리로 인한 코드 수정

### ISSUE THREAD

**Issue by nayoonk928** [Reservation-Purchase-System/product-service#3]
### Description
* stock_service 분리로 인한 코드 수정

### TODO
- [x] ProductStock 엔티티 및 repository 제거
- [x] StockClient 구현
- [x] 재고수량 요청 로직 삭제
- [x] 테스트 코드 수정
- [x] 로깅 테이블 추가
